export const stNTPCCY = new Meteor.Streamer('ntpccy')
export const stXS = new Meteor.Streamer('xs')
export const stSRVS = new Meteor.Streamer('srvs')
export const stXSKM = new Meteor.Streamer('xskm')
export const stNDMRC = new Meteor.Streamer('ndmrc')
export const stDNT = new Meteor.Streamer('dnt')